// <auto-generated />
using Final_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Final_Project.Migrations.FoodAccess
{
    //AutoAdded by Add-Migration command - Pratik Chaudhari
    [DbContext(typeof(FoodAccessContext))]
    partial class FoodAccessContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Final_Project.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("favoriteBreakfast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("favoriteDinner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("favoriteLunch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FoodRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            favoriteBreakfast = "Sandwitch",
                            favoriteDinner = "Burger",
                            favoriteLunch = "Pizza",
                            fullName = "Pratik Chaudhari"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
